version: "3.9"
networks:
  bridge-network:
    driver: bridge
services:
  backend:
    image: ana8os8mo/demoapp-backend:latest
    build: ./server
    ports:
      - 4000:4000
    networks:
      - bridge-network

  frontend:
    image: ana8os8mo/demoapp-frontend:latest
    build: ./spa
    ports:
      - 5000:80
    networks:
      - bridge-network